### PR TITLE
Ensure len(co_varnames) > 0 before reading first var name

### PR DESCRIPTION
**Pull request by Jongy**
Before this fix - a function like
```
def f():
   while 1:
       pass
```

would show as `[Error 1]`. Now it's not.

I still get
```
Ready to profile
1001 samples collected
0 samples lost
0 samples with truncated stack
1001 Python symbol errors
0 times Python symbol lost
0 kernel stack errors
0 errors
```

when running. Will look into what are those other errors...

### CODE REVIEW

**Comment by Jongy** [comment]
Found it:
```
$ tail -n 1 xyz.2021060114590975 | tr ';' '\n'
ipython3-2469289/2469289
home.jong..local.bin.ipython3.<module> (/home/jong/.local/bin/ipython3)_[p]
IPython.__init__.start_ipython (/usr/lib/python3/dist-packages/IPython/__init__.py)_[p]
traitlets.config.application.TerminalIPythonApp.launch_instance (/usr/lib/python3/dist-packages/traitlets/config/application.py)_[p]
IPython.terminal.ipapp.TerminalIPythonApp.start (/usr/lib/python3/dist-packages/IPython/terminal/ipapp.py)_[p]
IPython.terminal.interactiveshell.TerminalInteractiveShell.mainloop (/usr/lib/python3/dist-packages/IPython/terminal/interactiveshell.py)_[p]
IPython.terminal.interactiveshell.TerminalInteractiveShell.interact (/usr/lib/python3/dist-packages/IPython/terminal/interactiveshell.py)_[p]
IPython.core.interactiveshell.TerminalInteractiveShell.run_cell (/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py)_[p]
IPython.core.interactiveshell.TerminalInteractiveShell._run_cell (/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py)_[p]
IPython.core.async_helpers._pseudo_sync_runner (/usr/lib/python3/dist-packages/IPython/core/async_helpers.py)_[p]
[Error 1]_[pe]
IPython.core.interactiveshell.TerminalInteractiveShell.run_ast_nodes (/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py)_[p]
IPython.core.interactiveshell.TerminalInteractiveShell.run_code (/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py)_[p]
<ipython-input-2-c43e34e6d405>.<module> (<ipython-input-2-c43e34e6d405>)_[p]
<ipython-input-1-85f94142371b>.f (<ipython-input-1-85f94142371b>)_[p] 1
```

and from py-spy:
```
$ tail -n 1 utput | tr ';' '\n'
<module> (ipython3:8)
start_ipython (IPython/__init__.py:126)
launch_instance (traitlets/config/application.py:664)
start (IPython/terminal/ipapp.py:356)
mainloop (IPython/terminal/interactiveshell.py:558)
interact (IPython/terminal/interactiveshell.py:549)
run_cell (IPython/core/interactiveshell.py:2857)
_run_cell (IPython/core/interactiveshell.py:2886)
_pseudo_sync_runner (IPython/core/async_helpers.py:68)
run_cell_async (IPython/core/interactiveshell.py:3062)
run_ast_nodes (IPython/core/interactiveshell.py:3254)
run_code (IPython/core/interactiveshell.py:3331)
<module> (<ipython-input-5-c43e34e6d405>:1)
f (<ipython-input-1-85f94142371b>:3) 99
```

the problematic function is `run_cell_async`.

With an older version of PyPerf:
```
$ tail -n 1 xyz.2021060115281264 | tr ';' '\n'
ipython3-2469289/2469289
home.jong..local.bin.ipython3.<module> (/home/jong/.local/bin/ipython3)
IPython.__init__.start_ipython (/usr/lib/python3/dist-packages/IPython/__init__.py)
traitlets.config.application.TerminalIPythonApp.launch_instance (/usr/lib/python3/dist-packages/traitlets/config/application.py)
IPython.terminal.ipapp.TerminalIPythonApp.start (/usr/lib/python3/dist-packages/IPython/terminal/ipapp.py)
IPython.terminal.interactiveshell.TerminalInteractiveShell.mainloop (/usr/lib/python3/dist-packages/IPython/terminal/interactiveshell.py)
IPython.terminal.interactiveshell.TerminalInteractiveShell.interact (/usr/lib/python3/dist-packages/IPython/terminal/interactiveshell.py)
IPython.core.interactiveshell.TerminalInteractiveShell.run_cell (/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py)
IPython.core.interactiveshell.TerminalInteractiveShell._run_cell (/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py)
IPython.core.async_helpers._pseudo_sync_runner (/usr/lib/python3/dist-packages/IPython/core/async_helpers.py)
IPython.core.interactiveshell.run_cell_async (/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py)
IPython.core.interactiveshell.TerminalInteractiveShell.run_ast_nodes (/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py)
IPython.core.interactiveshell.TerminalInteractiveShell.run_code (/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py)
<ipython-input-6-c43e34e6d405>.<module> (<ipython-input-6-c43e34e6d405>)
<ipython-input-1-85f94142371b>.f (<ipython-input-1-85f94142371b>) 1
```

here we do see it - but without the class, although it does reside in a class. Our new error checking "found" this issue. Will look into it.

**Review by d3dave — CHANGES_REQUESTED** [review]
Doesn't compile with Clang 9 on Ubuntu 4.15.0-143-generic:
```
/virtual/main.c:499:16: error: variable-sized object may not be initialized
  char argname[max_t(size_t, sizeof("self"), sizeof("cls"))] = {};
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/linux/kernel.h:901:2: note: expanded from macro 'max_t'
        __max(type, type,                               \
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/linux/kernel.h:823:41: note: expanded from macro '__max'
#define __max(t1, t2, max1, max2, x, y) ({              \
                                        ^~~~~~~~~~~~~~~~~
1 error generated.
Failed to compiled PyPerf BPF programs: Unable to initialize BPF program
```

**Comment by Jongy** [comment]
Bleh, Linux...

**Comment by Jongy** [comment]
@d3dave try now please

**Comment by Jongy** [comment]
Although I'm not sure that my change addressed that error. Sigh

**Comment by d3dave** [comment]
```
bpf: Argument list too long. Program  too large (4433 insns), at most 4096 insns
```

**Comment by Jongy** [comment]
> ```
> bpf: Argument list too long. Program  too large (4433 insns), at most 4096 insns
> ```

Fixed, now there are 3396

File: examples/cpp/pyperf/PyPerfBPFProgram.cc [hunk 1]
```diff
@@ -473,14 +475,24 @@ get_first_arg_name(
...
   // Roughly equivalnt to the following in GDB:
   //
   //   ((PyTupleObject*)$frame->f_code->co_varnames)->ob_item[0]
   //
   void* args_ptr;
   result |= bpf_probe_read_user(&args_ptr, sizeof(void*), code_ptr + offsets->PyCodeObject.co_varnames);
-  result |= bpf_probe_read_user(&args_ptr, sizeof(void*), args_ptr + offsets->PyTupleObject.ob_item);
-  result |= bpf_probe_read_user_str(argname, maxlen, args_ptr + offsets->String.data);
+  result |= bpf_probe_read_user(&ob_size, sizeof(ob_size), args_ptr + offsets->String.size); // String.size is PyVarObject.ob_size
+  if (ob_size > 0) {
```
Comment (d3dave) [inline examples/cpp/pyperf/PyPerfBPFProgram.cc:486]: This shouldn't be in this function. It's better if it'd be in `get_classname` such that when this condition is false we skip the `first_self` and `first_cls` tests.

**Review by d3dave — CHANGES_REQUESTED** [review]

File: examples/cpp/pyperf/PyPerfBPFProgram.cc (hunk 1 above)
Comment (Jongy) [reply examples/cpp/pyperf/PyPerfBPFProgram.cc:486]: It kinda breaks up that function, then. (because now I will read `co_varnames` outside). So I can remove it altogether and inline it into `get_classname`.

Otoh, this is only to avoid 4 int comparisons? I think the API is legit this way.

Comment (d3dave) [reply examples/cpp/pyperf/PyPerfBPFProgram.cc:486]: 5 comparisons and 4 stores, I think.

Comment (Jongy) [reply examples/cpp/pyperf/PyPerfBPFProgram.cc:486]: Eh, this is not relevant in runtime. I think that merging the 2 functions will produce a less concise API

Comment (d3dave) [inline examples/cpp/pyperf/PyPerfBPFProgram.cc:486]: Also need `result != 0` here.

Comment (Jongy) [reply examples/cpp/pyperf/PyPerfBPFProgram.cc:486]: `bpf_probe_read_user` clears the buffer on error (so `ob_size` will be `0` if this call fails). If the previous call fails, then we are reading from `0 + offsets->String.size` which will fail as well (NULL page read, ...).

But for correctness, okay

Comment (d3dave) [reply examples/cpp/pyperf/PyPerfBPFProgram.cc:486]: Hmm, touché 👍

**Review by d3dave — APPROVED** [review]

**Comment by Jongy** [comment]
3481 insns
